= Crux Database Plugin

This is a plugin for Fulcro RAD that adds support for using Crux databases as the back-end technology.

This repo is a fork of https://github.com/fulcrologic/fulcro-rad-datomic adapted to Crux api with some Datomic specific features dropped (e.g. schemas and Datomic Cloud support).

== Configuration

There is an example application https://github.com/fulcrologic/fulcro-rad-demo[fulcrologic/fulcro-rad-demo] that can be referenced for how to properly configure this plugin.

`crux-adapter/start-databases` expects a map with `:com.fulcrologic.rad.database-adapters.crux/databases` key that contains configuration maps for each defined database.
 Configuration maps are then passed directly to `crux.api/start-node` so please refer to https://opencrux.com/reference/21.02-1.15.0/configuration.html[Crux documentation] for available options.

[source, clojure]
-----
:com.fulcrologic.rad.database-adapters.crux/databases
    {:main {:crux.jdbc/connection-pool {:dialect #:crux{:module "crux.jdbc.psql/->dialect"}
                                        :db-spec {:dbname   "fulcro-rad-demo"
                                                             :user     "postgres"
                                                             :password "postgres"}}
            :crux/tx-log               {:crux/module "crux.jdbc/->tx-log"
                                        :connection-pool :crux.jdbc/connection-pool}
            :crux/document-store       {:crux/module "crux.jdbc/->document-store"
                                        :connection-pool :crux.jdbc/connection-pool}}}
-----

Because Crux expects module names to be symbols, there's a convenience function `crux-adapter/symbolize-crux-modules` that symbolizes values under `:crux/module` so you can store them as strings in edn file.

[source, clojure]
-----
(require '[com.fulcrologic.rad.database-adapters.crux :as crux])

(crux/start-databases (crux/symbolize-crux-modules config))
-----



== LICENSE

The MIT License (MIT)
Copyright (c), Fulcrologic, LLC

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
documentation files (the "Software"), to deal in the Software without restriction, including without limitation the
rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit
persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the
Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
